# Generated by Django 5.2 on 2025-06-06 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code_flag', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('phone_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Domicile',
            fields=[
                ('domicile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contactos.country')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name_p', models.CharField(max_length=50)),
                ('last_name_m', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('discord_account', models.URLField(blank=True, default='')),
                ('github_account', models.URLField(blank=True, default='')),
                ('domicile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contactos.domicile')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contactos.group')),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contactos.phonenumber')),
            ],
        ),
    ]
